Fix crash when ranger instance has not yet entered directory
>   File "/root/.config/ranger/plugins/main/__init__.py", line 43, in hook_init
>     check_use_color()
>   File "/root/.config/ranger/plugins/main/__init__.py", line 34, in check_use_color
>     fm.reload_cwd()
>   File "/usr/src/repos/ranger/.worktrees/master/ranger/core/actions.py", line 162, in reload_cwd
>     cwd.unload()
>     ^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'unload'

(Sorry to not catch it before, got a tmux shortcut to launch ranger so this didn't trigger..)